const ALBUM_TITLE_MAX_CHARS: number = 30
const POST_TITLE_MAX_CHARS: number = 30
const POST_BODY_MAX_CHARS: number = 80
const AMOUNT_OF_FIRST_PHOTOS_FROM_ALBUM: number = 5

export {
  ALBUM_TITLE_MAX_CHARS,
  POST_TITLE_MAX_CHARS,
  POST_BODY_MAX_CHARS,
  AMOUNT_OF_FIRST_PHOTOS_FROM_ALBUM,
}
